# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Stakes' do
pod 'FZAccordionTableView', '~> 0.1.2'
pod 'Firebase', '>= 2.5.1'
pod 'JSQMessagesViewController'
pod 'STTwitter'
pod 'Masonry'
pod ‘AFNetworking’
pod ‘BALoadingView’
end

target 'StakesTests' do

end

target 'StakesUITests' do

end

